services:
  postgres:
    container_name: postgres-sql-wac
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: whatsapp_clone
    volumes:
      - postgres:/data/postgres
    ports:
      - 5433:5432
    networks:
      - whatsapp-clone
    restart: unless-stopped


  keycloak:
    container_name: keycloak-wac
    image: quay.io/keycloak/keycloak:24.0.2
    command: [ 'start-dev']
    ports:
      - 9090:8080
    volumes:
      #- ./realm-config:/opt/keycloak/data/import
      - keycloak-whatsapp-data:/opt/keycloak/data
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - whatsapp-clone



networks:
  whatsapp-clone:
    driver: bridge

volumes:
  postgres:
  keycloak-whatsapp-data: